/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        'profile_bg': "url('./images/profile_bg.png')",
        'logo1_white': "url('./images/logo1_white.png')",
        'logo2_white': "url('./images/logo2_white.png')",
        'logo1_black': "url('./images/logo1_black.png')",
        'logo2_black': "url('./images/logo2_black.png')",
        'home_bg': "url('./images/home_background.png')",
        'home2_bg': "url('./images/home2_background.png')",
        'img1': "url('./images/img1.png')",
        'img2': "url('./images/img2.png')",
        'img3': "url('./images/img3.png')",
        'img4': "url('./images/img4.png')",
        'img5': "url('./images/img5.png')",
        'big_img1': "url('./images/big_img1.png')",
        'big_img2': "url('./images/big_img2.png')",
        'big_img3': "url('./images/big_img3.png')",
        'login_img': "url('./images/login.png')",
        'team': "url('./images/team.jpg')",
        'product1': "url('./images/product1.png')",
        'product2': "url('./images/product2.png')",
        'product3': "url('./images/product3.png')",
        'product4': "url('./images/product4.png')",
        'product5': "url('./images/product5.png')",
        'product6': "url('./images/product6.png')",
        'product7': "url('./images/product7.png')",
        'product8': "url('./images/product8.png')",
        'product9': "url('./images/product9.png')",
        'product10': "url('./images/product10.png')",
        'product11': "url('./images/product11.png')",
        'product12': "url('./images/product12.png')",
        'shopwp': "url('./images/shopwp.png')",
        'mail': "url('./images/mail.svg')",
        'me': "url('./images/me.png')",
        'musk': "url('./images/musk.png')",
        'bezos': "url('./images/bezos.png')",
        'about1': "url('./images/about1.png')",
        'about2': "url('./images/about2.png')",
        'about3': "url('./images/about3.png')",
        'about4': "url('./images/about4.png')",
        'aboutcareer': "url('./images/aboutcareer.png')",
        'aboutdesign': "url('./images/aboutdesign.png')",
        'abouthistory': "url('./images/abouthistory.png')",
        'aboutsustainability': "url('./images/aboutsustainability.png')",
        'team': "url('./images/team.png')",
        'payfail': "url('./images/payfail.png')",
        'paysuccess': "url('./images/paysuccess.png')",
        'headphone': "url('./images/headphone.png')",
        'tablet': "url('./images/tablet.png')",
        'webcamvideo': "url('./images/webcamvideo.png')",
        'streaming': "url('./images/streaming.png')",
        'micekeyboard': "url('./images/micekeyboard.png')",
        '1': "url('./images/1.jpg')",
        '2': "url('./images/2.jpg')",
        '3': "url('./images/3.jpg')",
        '4': "url('./images/4.jpg')",
        '5': "url('./images/5.jpg')",
      },
    },
    colors: {
      footer: '#252a2c',
      white: '#FFFFFF',
      black: '#000000',
      light_grey: '#F0F0F0',
      purple: '#12D3F4',
      grey: '#BEBEBE',
      green: '#34B233',
      red: '#FF0000',
      fail: '#E91640'
    }
  },
  plugins: [],
}
